### ISSUE TITLE
netplan instead of interfaces

### ISSUE THREAD

**Issue by tuxmea** [betadots/linux_ha-training#13]
provide working examples for netplan based config

```yaml
/etc/netplan/99-bonding.yaml
network:
  version: 2
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bonds:
    bond0:
      interfaces: [eth1, eth2]
      addresses: [10.100.10.11/24]
      parameters:
        mode: active-backup
        primary: eth1
        mii-monitor-interval: 100
        up-delay: 200
        down-delay: 200
```
